version: "3.8"

services:
  react-app:
    build: .
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules # node_modulesはホスト側のと分離
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
